solve task2
valerak2/CollectionsTask pull request #1
Opened 2023-04-01 19:01 UTC by valerak2

2023-04-08 13:09 UTC, vpyzhyanov requested changes

2023-04-08 13:09 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * (если возникнут коллизии, то О(n))
Никаких "если"!!! Вы должны гарантировать сложность. И обосновать, что вы её гарантируете (требование пункт 3)

2023-04-08 13:09 UTC, vpyzhyanov commented on src/main/java/Bartender.java
> +    private static final HashMap<Ticket,String> listOfOrders = new HashMap<>();
Почему коллекция статическая? Хотя сам класс нет. Такие небольшие оплошности в больших проектах приведут к большим проблемам.

2023-04-15 09:10 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * (если возникнут коллизии, то О(n))
**Нет ответа!!!**

2023-04-15 09:10 UTC, vpyzhyanov commented on src/main/java/Bartender.java
> +    private static final HashMap<Ticket,String> listOfOrders = new HashMap<>();
**Нет ответа!!!**

2023-04-15 09:10 UTC, vpyzhyanov commented
Зачем вы переводите задачу на проверку, если вы не ответили ни на один вопрос?

2023-04-15 09:14 UTC, vpyzhyanov requested changes

2023-04-15 09:14 UTC, vpyzhyanov commented on src/main/java/Bartender.java
> +    private final HashMap<Ticket,String> listOfOrders = new HashMap<>();
Теперь использование интерфейсов обязательно

2023-04-15 09:14 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * (если возникнут коллизии, то О(n))
Обоснование, что вы достигаете этой сложности так и не появилось

2023-05-23 19:07 UTC, valerak2 commented on src/main/java/Bartender.java
> +    private static final HashMap<Ticket,String> listOfOrders = new HashMap<>();
исправил, убрал статик

2023-05-23 19:08 UTC, valerak2 commented on src/main/java/Bartender.java
> +    private final HashMap<Ticket,String> listOfOrders = new HashMap<>();
исправил на Map<Ticket,String>

2023-05-23 19:09 UTC, valerak2 commented on src/main/java/Main.java
> + * (если возникнут коллизии, то О(n))
Дополнил обоснование в последнем коммите. обоснование находятся в JavaDoc класса Main

2023-05-29 20:10 UTC, vpyzhyanov requested changes

2023-05-29 20:10 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * поэтому сложность алгоритма О(n).
Это неправильно

2023-05-30 20:25 UTC, closed without merging