solve task4
valerak2/CollectionsTask pull request #2
Opened 2023-04-03 15:49 UTC by valerak2

2023-04-08 13:18 UTC, vpyzhyanov requested changes

2023-04-08 13:18 UTC, vpyzhyanov commented on pom.xml
> +            <version>${guava.version}</version>
зависимости описаны не по правилам!!!

2023-04-08 13:18 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * то в этих случаях лучше использовать multimap, чтобы по одному ключу хранить множество значений.
это можно делать и без multimap, достаточно стандартных коллекций для этого

2023-04-08 13:18 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * Операции добавления, удаления выполняются за O(1)
нет обоснования. Она может и за линейную сложность выполняться.

Для **каждой** коллекции нужно обоснование!

2023-04-08 13:18 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * Операция поиска по временному интервалу выполняется за O(n),
слишком долго!

2023-04-08 13:18 UTC, vpyzhyanov commented on src/main/java/Library.java
> +    private final HashMultimap<String, Book> authorOnBook = HashMultimap.create();
Пользуйтесь интерфейсами! Теперь это обязательно

2023-04-15 09:17 UTC, vpyzhyanov commented
Зачем вы переводите задачу на проверку, если вы не ответили ни на один вопрос?

2023-04-15 09:23 UTC, vpyzhyanov commented on src/main/java/Library.java
> +    private void addValue(Map<String, Map<String, Book>> map, String key, Book book) {
Map внутри Map - вы хотите всех запутать? Зачем это всё? 

Зачем отделять называние книги (особенно с учётом того, что вы ни разу этим не пользуетесь)?

2023-04-15 09:23 UTC, vpyzhyanov commented on src/main/java/Library.java
> +    private final Map<String, Map<String, Book>> yearOnBook = new HashMap<>();
Неправильный тип данных. Год - это integer

2023-04-15 09:23 UTC, vpyzhyanov commented on src/main/java/Library.java
> +                bookList.addAll(yearOnBook.get(String.valueOf(year)).values());
бессмысленные преобразования из одного типа в другой

2023-04-15 09:23 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * Операция поиска по временному интервалу выполняется за O(n),
**Нет ответа!!!**

2023-05-23 20:48 UTC, valerak2 commented on src/main/java/Library.java
> +    private void addValue(Map<String, Map<String, Book>> map, String key, Book book) {
Исправил структуры данных

2023-05-23 20:48 UTC, valerak2 commented on src/main/java/Library.java
> +    private final Map<String, Map<String, Book>> yearOnBook = new HashMap<>();
Исправил

2023-05-23 20:49 UTC, valerak2 commented on src/main/java/Library.java
> +                bookList.addAll(yearOnBook.get(String.valueOf(year)).values());
Удалил ненужное преобразование

2023-05-23 21:41 UTC, valerak2 commented on src/main/java/Main.java
> + * Операция поиска по временному интервалу выполняется за O(n),
Я думаю быстрее чем за O(n), используя стандартные коллекции, поиск по временному интервалу не сделать.
Так как для решения этой задачи подходит только перебор по ключам словаря и метод subMap(fromKey,
 toKey) у SortedMap, который точно быстрее чем O(n)
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/TreeMap.html#subMap(K,K)
Но тут возникает проблема с хранением и преобразованием SortedMap
Если мы прямо в методе поиска по временному интервалу будем преобразовывать Неотсортированный словарь в отсортированный, то сложность такого преобразования будет уже O(n*log(n)).
Или если мы будем изначально хранить книги по годам в SortedMap, то возрастет сложность остальных методов(добавление, удаление, поиск) с O(1) до O(log(n)).
Поэтому я считаю что за O(n) это эффективнее всего. Или я не догадался до более эффективного метода

2023-05-29 20:16 UTC, vpyzhyanov commented on src/main/java/Library.java
> +        if (!authorOnBook.containsKey(book.author())) {
удобнее использовать computeIfAbsent()

2023-05-30 20:28 UTC, closed without merging