solve task5
valerak2/CollectionsTask pull request #3
Opened 2023-04-05 22:57 UTC by valerak2

2023-04-08 13:25 UTC, vpyzhyanov requested changes

2023-04-08 13:25 UTC, vpyzhyanov commented on src/main/java/ManagementSystem.java
> +    public void getResult() {
А где сам результат? А ведь он необходим по условию задачи!

Если метод начинается с get, значит он должен что-то вернуть, он не может быть void. Ибо это бессмыслица.

2023-04-08 13:25 UTC, vpyzhyanov commented on src/main/java/Main.java
> +        calculationManagementSystem.getResult();
что толку получить результат, которого нет

2023-04-08 13:25 UTC, vpyzhyanov commented on src/main/java/Main.java
> + * и снова обращаемся за результатом и в итоге опять О(1)*/
Не понял смысла этого абзаца

2023-04-15 09:23 UTC, vpyzhyanov commented
Зачем вы переводите задачу на проверку, если вы не ответили ни на один вопрос?

2023-05-23 21:51 UTC, valerak2 commented on src/main/java/ManagementSystem.java
> +    public void getResult() {
Добавил результат

2023-05-23 21:52 UTC, valerak2 commented on src/main/java/Main.java
> + * и снова обращаемся за результатом и в итоге опять О(1)*/
Исправил обоснование выбора структуры данных

2023-05-29 20:18 UTC, vpyzhyanov requested changes
Забыл нажать Submit review в прошлый раз(

2023-05-29 20:18 UTC, vpyzhyanov commented on src/main/java/Main.java
> +        calculationManagementSystem.printResultOnTask();
Ровным счётом ничего не изменилось. Как результат не выдавался, так он и не выдаётся.

Грубая ошибка с точки зрения ООП. Класс управления расчётами не должен знать ни о какой консоли. Это не его сфера ответственности.

2023-05-29 20:18 UTC, vpyzhyanov commented on src/main/java/SomeFunction.java
> +    Double getResult();
Ну что вы делаете? Зачем изобретать свой велосипед? Когда есть готовые? Используйте Callable вместо Runnable или вообще Function

2023-05-29 20:23 UTC, vpyzhyanov commented on src/main/java/Main.java
> +        calculationOfBankCredits function2 = new calculationOfBankCredits(requestedAmount, rateOfInterest);
Классы именуются с большой буквы

2023-05-29 20:23 UTC, vpyzhyanov commented on src/main/java/calculationOfBankCredits.java
> +public class calculationOfBankCredits implements SomeFunction {
Классы именуются с большой буквы. А ещё у них должен быть JavaDoc

2023-05-30 20:30 UTC, closed without merging